steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast3-docker.pkg.dev/feanut/feanut-backend:$_BUILG_TAG',
        '.',
      ]
images:
  - 'asia-northeast3-docker.pkg.dev/feanut/feanut-backend:$_BUILG_TAG'
