export const PROMOTION_SCHOOL_MODULE_NAME = 'promotion_schools';

export const PROMOTION_SCHOOL_SCHEMA_NAME = PROMOTION_SCHOOL_MODULE_NAME;

export const PROMOTION_SCHOOL_STUDENT_SCHEMA_NAME =
  PROMOTION_SCHOOL_MODULE_NAME + '_students';

export const PROMOTION_SCHOOL_VOTE_SCHEMA_NAME =
  PROMOTION_SCHOOL_MODULE_NAME + '_votes';
