export const POLLING_MODULE_NAME = 'pollings';
export const USERROUND_NAME = 'userround';

export const POLLING_ERROR_EXIST_POLLING = 1;
export const POLLING_ERROR_EXIST_USERROUND = 2;
export const POLLING_ERROR_NOT_INCLUDES_POLLID = 3;
export const POLLING_ERROR_NOT_FOUND_POLLING = 4;
export const POLLING_ERROR_NOT_FOUND_USERROUND = 5;
export const POLLING_ERROR_COOL_TIME = 6;
