export const AUTH_MODULE_NAME = 'auth';

export const AUTH_ERROR_EXIST_USERNAME = 1;
export const AUTH_ERROR_NOTFOUND_USERNAME = 1;
export const AUTH_ERROR_EXIST_PHONE_NUMBER = 2;
export const AUTH_ERROR_INVALID_CODE = 3;
export const AUTH_ERROR_VERIFICATION_TIMEOUT = 3;

export const AUTH_ERROR_SIGNIN_COOL_TIME = 99;
