export const AUTH_MODULE_NAME = 'auth';

export const AUTH_ERROR_EXIST_PHONE_NUMBER = 1;
export const AUTH_ERROR_NOT_FOUND_PHONE_NUMBER = 2;
export const AUTH_ERROR_INVALID_CODE = 3;
export const AUTH_ERROR_COOL_TIME = 4;
export const AUTH_ERROR_VERIFICATION_TIMEOUT = 5;
export const AUTH_ERROR_NOT_FOUND_USER = 6;
export const AUTH_ERROR_INVAILD_VERIFICATION = 7;
export const AUTH_ERROR_INVAILD_REFRESH_TOKEN = 8;

export const INSTAGRAM_AUTH_REDIRECT_PATH = '/oauth/instagram';
